name: General Election 2024 candidates

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '17 5 * 5,6,7 *'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ge2024.yml'



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: |
            JSON::XS

      # Runs script
      - name: Update candidates
        working-directory: ./
        run: |
          perl pipelines/society/general-elections.pl

      - name: Commit changes to files
        working-directory: ./
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/_data/sources/society/general-elections-2024.csv
          git add src/_data/sources/society/general-elections-notional.csv
          git add src/themes/society/general-elections/index.njk
          git commit -m "Update General Election 2024 candidates" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
