name: Update ATMs

"on":
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 5 1 * *"

# Cancel any in-flight jobs
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: cpanfile

      # Runs script
      - name: Update ATMs
        working-directory: ./
        run: |
          perl pipelines/economy/atms.pl

      - name: Commit changes to files
        working-directory: ./
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/themes/economy/atms/_data/release/link.csv
          git add src/themes/economy/atms/_data/total.json
          git add src/themes/economy/atms/index.vto
          git commit -m "Update ATMs" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


